diff --git a/backend/alembic.ini b/backend/alembic.ini
new file mode 100644
index 0000000000000000000000000000000000000000..0f0d218186f246bcd2a9c5ba18b24f59f26af148
--- /dev/null
+++ b/backend/alembic.ini
@@ -0,0 +1,28 @@
+[alembic]
+script_location = alembic
+sqlalchemy.url = postgresql+psycopg2://postgres:postgres@localhost:5432/kamla_horeca
+
+[loggers]
+keys = root,sqlalchemy,alembic
+[handlers]
+keys = console
+[formatters]
+keys = generic
+[logger_root]
+level = WARN
+handlers = console
+[logger_sqlalchemy]
+level = WARN
+handlers =
+qualname = sqlalchemy.engine
+[logger_alembic]
+level = INFO
+handlers =
+qualname = alembic
+[handler_console]
+class = StreamHandler
+args = (sys.stderr,)
+level = NOTSET
+formatter = generic
+[formatter_generic]
+format = %(levelname)-5.5s [%(name)s] %(message)s
